general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  master_key: os.environ/PROXY_MASTER_KEY
  database_connection_pool_limits: 10
  allow_requests_on_db_unavailable: True

litellm_settings:
  request_timeout: 600 # raise Timeout error if call takes longer than 600 seconds. Default value is 6000seconds if not set
  set_verbose: False # Switch off Debug Logging, ensure your logs do not have any debugging on
  json_logs: false # Get debug logs in json format
  drop_params: True